server:
  port: 8010

spring:
  datasource:
    url: jdbc:postgresql://localhost/masterdtabase
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 7727ww7727
    sql-script-encoding: utf-8

  jpa:
    generate-ddl: true
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: create

  freemarker:
    suffix: .ftl
    expose-request-attributes: false

  servlet:
    multipart:
      max-file-size: 20000000
      file-size-threshold: 20000000

#  mail:
#    host: smtp.yandex.com
#    port: 25
#    username: johndeathsmell@yandex.by
#    password: 7727ww7727
#    protocol: smtp
